version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: my_shop_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shop_db
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_password
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shop_network

networks:
  shop_network:
    driver: bridge
